<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-29 14:57

=======
>>>>>>> 3bdabc9b16dc06f179d348ac84bbc6d6311c94bc
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_note_unique_per_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at']},
        ),
    ]
