# Generated by Django 6.0.4 on 2026-04-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_note_options'),
        ('mainapp', '0005_notecomment'),
    ]

    operations = [
    ]
